config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/' => 'homes#top', as: 'top'
    get 'search' => 'items#search', as: 'search'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root 'homes#top'
    get 'search' => 'items#search', as: 'search'
    get '/about' => 'homes#about', as: 'about'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#new'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :index, :create, :show]
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def finally_address
  '〒' + postal_code + ' ' + destination + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders
  
  validates :first_name,presence:true
  validates :last_name,presence:true
  validates :first_name_kana,presence:true
  validates :last_name_kana,presence:true
  validates :postal_code,presence:true
  validates :address,presence:true
  validates :telephone_number,presence:true
  
  def full_name
    first_name + " " + last_name
  end
  
  def full_name_kana
    first_name_kana + " " + last_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  has_one_attached :image
  
  def with_tax_price
    (price * 1.1).ceil
    # ceilは切り上げ、floorが切り捨て、roundが四捨五入
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, confirm_deposit: 1, in_production: 2, preparing_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { cannot_start: 0, waiting_start: 1, in_production: 2, completed: 3 }
  
  def subtotal
    price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :first_name_kana, :last_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params  
    params.require(:genre).permit(:name)
  end  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  def search
    if params[:name].present?
      @items = Item.where('name like ?', "%#{params[:name]}%")
    else
      @items = Item.all
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :image, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = @order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
    # @total = @order_details.sum { |order_detail| order_detail.subtotal }
    @customer = @order.customer
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "confirm_deposit"
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end
  
  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/_index.html.erb
<table class="mx-auto">
	<thead>
		<tr class="bg-light border-top">
			<th>会員ID</th>
			<th>氏名</th>
			<th>メールアドレス</th>
			<th>ステータス</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% customers.each do |customer| %>
			<tr class="border-top border-bottom">
				<td><%= customer.id %></td>
				<td><%= link_to customer.full_name, admin_customer_path(customer), class: "border-bottom text-dark" %></td>
				<td><%= customer.email %></td>
				<td>
					<% if customer.is_active? %>
						<span class="text-success">有効</span>
					<% else %>
						<span class="text-dark">退会</span>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/customers/edit.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block"><%= @customer.full_name %>さんの会員情報編集</h2>
	<%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
		<table>
			<thead>
				<th></th>
				<th></th>
				<th></th>
			</thead>
			<tbody>
			  <tr>
					<td>会員ID</td>
					<td><%= @customer.id %></td>
				</tr>
				<tr>
					<td>氏名</td>
					<td><%= f.text_field :first_name, :placeholder =>"#{@customer.first_name}" %></td>
					<td><%= f.text_field :last_name, :placeholder =>"#{@customer.last_name}" %></td>
				</tr>
				<tr>
					<td>フリガナ</td>
					<td><%= f.text_field :first_name_kana, :placeholder =>"#{@customer.first_name_kana}" %></td>
					<td><%= f.text_field :last_name_kana, :placeholder =>"#{@customer.last_name_kana}" %></td>
				</tr>
				<tr>
					<td>郵便番号</td>
					<td><%= f.text_field :postal_code, :placeholder =>"#{@customer.postal_code}" %></td>
				</tr>
				<tr>
					<td>住所</td>
					<td><%= f.text_field :address, :placeholder =>"#{@customer.address}" %></td>
				</tr>
				<tr>
					<td>電話番号</td>
					<td><%= f.text_field :telephone_number, :placeholder =>"#{@customer.telephone_number}" %></td>
				</tr>
				<tr>
					<td>メールアドレス</td>
					<td><%= f.email_field :email, autocomplete: "email", :placeholder =>"#{@customer.email}" %></td>
				</tr>
				<tr>
					<td>会員ステータス</td>
					<td>
					  <%= f.radio_button :is_active, true %><%= f.label :is_active, "有効" %>
	          <%= f.radio_button :is_active, false %><%= f.label :is_active, "退会" %>
	        </td>
				</tr>
				<tr>
				  <td></td>
					<td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
				</tr>
			</tbody>
		</table>
	<% end %>
</section>

app/views/admin/customers/index.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block">会員一覧</h2>
	<%= render 'index', customers: @customers %>
</section>

app/views/admin/customers/show.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block"><%= @customer.full_name %>さんの会員詳細</h2>
	<table class="m-3">
		<thead>
			<th></th>
			<th></th>
			<th></th>
		</thead>
		<tbody>
			<tr>
				<td>会員ID</td>
				<td><%= @customer.id %></td>
			</tr>
			<tr>
				<td>氏名</td>
				<td><%= @customer.first_name %> <%= @customer.last_name %></td>
			</tr>
			<tr>
				<td>フリガナ</td>
				<td><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
			</tr>
			<tr>
				<td>郵便番号</td>
				<td><%= @customer.postal_code %></td>
			</tr>
			<tr>
				<td>住所</td>
				<td><%= @customer.address %></td>
			</tr>
			<tr>
				<td>電話番号</td>
				<td><%= @customer.telephone_number %></td>
			</tr>
			<tr>
				<td>メールアドレス</td>
				<td><%= @customer.email %></td>
			</tr>
			<tr>
				<td>会員ステータス</td>
				<td>
					<% if @customer.is_active? %>
						<span class="text-success">有効	</span>					
					<% else %>
						<span class="text-dark">退会済み</span>
					<% end %>
				</td>
			</tr>
			<tr>
				<td></td>
				<td><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></td>
				<td><%= link_to "注文履歴一覧を見る", admin_top_path, class: "btn btn-primary" %></td>
			</tr>
		</tbody>
	</table>
	
</section>