config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/' => 'homes#top', as: 'top'
    get 'search' => 'items#search', as: 'search'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root 'homes#top'
    get 'search' => 'items#search', as: 'search'
    get '/about' => 'homes#about', as: 'about'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#new'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :index, :create, :show]
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def finally_address
  '〒' + postal_code + ' ' + destination + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders
  
  validates :first_name,presence:true
  validates :last_name,presence:true
  validates :first_name_kana,presence:true
  validates :last_name_kana,presence:true
  validates :postal_code,presence:true
  validates :address,presence:true
  validates :telephone_number,presence:true
  
  def full_name
    first_name + " " + last_name
  end
  
  def full_name_kana
    first_name_kana + " " + last_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  has_one_attached :image
  
  def with_tax_price
    (price * 1.1).ceil
    # ceilは切り上げ、floorが切り捨て、roundが四捨五入
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, confirm_deposit: 1, in_production: 2, preparing_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { cannot_start: 0, waiting_start: 1, in_production: 2, completed: 3 }
  
  def subtotal
    price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params  
    params.require(:genre).permit(:name)
  end  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  def search
    if params[:name].present?
      @items = Item.where('name like ?', "%#{params[:name]}%")
    else
      @items = Item.all
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :image, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    @total = @order_details.inject(0) { |sum, order_detail| sum + order_detail.subtotal }
    # @total = @order_details.sum { |order_detail| order_detail.subtotal }
    @customer = @order.customer
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "confirm_deposit"
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end
  
  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def after_sign_in_path_for(resource)
    admin_top_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model: genre, url: url do |f| %>
	<%= f.label :name, "ジャンル名" %>
	<%= f.text_field :name, :placeholder =>"ジャンル名" %>

	<%= f.submit submit, class: "btn btn-success ml-3" %>
<% end %>

app/views/admin/genres/edit.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block">ジャンル編集</h2>
  <%= render 'form', genre: @genre, url: admin_genre_path(@genre), submit: '変更を保存' %>
</section>

app/views/admin/genres/index.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block">ジャンル一覧・追加</h2>

  <%= render 'form', genre: @genre, url: admin_genres_path, submit: '新規登録' %>

	<table class="mt-3">
		<thead>
			<tr class="border-top bg-light">
				<th>ジャンル</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @genres.each do |genre| %>
				<tr class="border-top border-bottom">
					<td><%= genre.name %></td>

					<td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</section>

app/views/admin/items/_form.html.erb
<%= form_with model: item, url: url do |f| %>
	<table class="mx-auto">
		<thead>
			<tr>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= f.label :image, "商品画像" %></td>
				<td><%= f.file_field :image,  accept:'image/*' %></td>
			</tr>
			<tr>
				<td><%= f.label :name, "商品名" %></td>
				<td><%= f.text_field :name, :placeholder =>"商品名" %></td>
			</tr>
			<tr>
				<td><%= f.label :introduction, "商品説明" %></td>
				<td><%= f.text_area :introduction, rows: 3, :placeholder =>"ここに説明文を記述します" %></td>
			</tr>
			<tr>
				<td><%= f.label :genre_id, "ジャンル" %></td>
				<td class="select_field"><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --" %></td>
			</tr>
			<tr>
				<td><%= f.label :price, "税抜価格" %></td>
				<td><%= f.number_field :price, :placeholder =>"1000" %>円</td>
			</tr>
			<tr>
				<td><%= f.label :sales_status, "販売ステータス" %></td>
				<td class="select_field">
					<%= f.radio_button :is_active, true %>
					<%= f.label :is_active, "販売中" %>
					<%= f.radio_button :is_active, false %>
					<%= f.label :is_active, "販売停止中" %>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="text-center">
		<%= f.submit submit, class: "btn btn-success m-3" %>
	</div>
<% end %>

app/views/admin/items/_index.html.erb
<table class="mx-auto">
	<thead>
		<tr class="bg-light">
			<th>商品ID</th>
			<th>商品名</th>
			<th>税抜価格</th>
			<th>ジャンル</th>
			<th>ステータス</th>
		</tr>
	</thead>
	<tbody>
		<% items.each do |item| %>
			<tr>
				<td><%= item.id %></td>
				<td><%= link_to item.name, admin_item_path(item), class: "border-bottom text-dark" %></td>
				<td><%= item.price %></td>
				<td><%= link_to item.genre.name, admin_items_path(genre_id: item.genre_id), class: "text-dark" %></td>
				<td>
					<% if item.is_active? %>
						<span class="text-success">販売中</span>
					<% else %>
						<span class="text-dark">販売停止中</span>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/items/edit.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block">商品編集</h2>
  <%= render 'form', item: @item, url: admin_item_path(@item), submit: '変更を保存' %>
</section>

app/views/admin/items/index.html.erb
<section class="container">
	<div class="row justify-content-around">
		<h2 class="bg-light m-3">商品一覧</h2>

		<h3 class="text-right m-3">
			<%= link_to "+", new_admin_item_path, class: "text-dark btn shadow rounded-circle p-0", style: "width:2rem;height:2rem;" %>
		</h3>
	</div>	
	<%= render 'admin/items/index', items: @items %>

</section>

app/views/admin/items/new.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block">商品新規登録</h2>
  <%= render 'form', item: @item, url: admin_items_path, submit: '新規登録' %>
</section>

app/views/admin/items/search.html.erb
<section class="container">
	<div class="row justify-content-around">
		<h2 class="bg-light m-3">商品一覧</h2>

		<h3 class="text-right m-3">
			<%= link_to "+", new_admin_item_path, class: "text-dark btn shadow rounded-circle p-0", style: "width:2rem;height:2rem;" %>
		</h3>
	</div>	
	<%= render 'admin/items/index', items: @items %>

</section>

app/views/admin/items/show.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block">商品詳細</h2>
	<div class="row justify-content-around">
		<div>
			<% if @item.image.attached? %>
        <%= image_tag @item.image, size: "300x300" %>
      <% else %>
        <%= image_tag 'no_image', size: "300x300" %>
      <% end %>
		</div>
		<table>
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>商品名</td>
					<td><%= @item.name %></td>
				</tr>
				<tr>
					<td>商品説明</td>
					<td><%= @item.introduction %></td>
				</tr>
				<tr>
					<td>ジャンル</td>
					<td><%= @item.genre.name %></td>
				</tr>
				<tr>
					<td>税込価格<br>(税抜価格)</td>
					<td><%= @item.with_tax_price %>(<%= @item.price %>)円</td>
				</tr>
				<tr>
					<td>販売ステータス</td>
					<td>
						<% if @item.is_active? %>
							<span class="text-success">販売中</span>
						<% else %>
							<span class="text-dark">販売停止中</span>
						<% end %>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="text-center">
		<%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
	</div>
</section>

app/views/admin/orders/show.html.erb
<section class="container">
	<h2 class="bg-light m-3 d-inline-block">注文履歴詳細</h2>
	<table>
		<thead>
			<tr>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>購入者</td>
				<td class="d-inline-block border-bottom"><%= link_to @customer.full_name, admin_customer_path(@customer), class: "text-dark" %></td>
			</tr>
			<tr>
				<td>注文日</td>
				<td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
			</tr>
			<tr>
				<td>配送先</td>
				<td>
					〒<%= @order.postal_code %>
					<%= @order.destination %><br>
					<%= @order.name %>
				</td>
			</tr>
			<tr>
				<td>支払方法</td>
				<td><%= @order.payment_method_i18n %></td>
			</tr>
			<tr>
				<td>注文ステータス</td>
				<td>
					<%= form_with model: @order, url: admin_order_path(@order) do |f| %>
						<%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
						<%= f.submit "更新", class: "btn btn-success" %>
					<% end %>
				</td>
			</tr>
		</tbody>
	</table>
	<div class="row justify-content-around mt-3">
		<table>
			<thead>
				<tr class="bg-light">
					<th>商品名</th>
					<th>単価(税込)</th>
					<th>数量</th>
					<th>小計</th>
					<th>制作ステータス</th>
				</tr>
			</thead>
			<tbody>
			  <% @sum = 0 %>
				<% @order_details.each do |order_detail| %>
					<% item = order_detail.item %>
					<tr>
						<td><%= link_to item.name, admin_item_path(item), class: "text-dark" %></td>
						<td class="text-center"><%= order_detail.price %></td>
						<td class="text-center"><%= order_detail.amount %></td>
						<td class="text-center"><%= order_detail.subtotal.to_s(:delimited) %></td>
						<td>
							<%= form_with model: order_detail, url: admin_order_order_detail_path(order_id: @order.id, id: order_detail.id) do |f| %>
								<%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
								<%= f.submit "更新", class: "btn btn-success" %>
							<% end %>
						</td>
					</tr>
					<% @sum += order_detail.subtotal %>
				<% end %>
			</tbody>
		</table>

		<table>
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>商品合計</td>
					<td><%= @sum.to_s(:delimited) %>円</td>
					<td><%= @total.to_s(:delimited) %>円</td>
				</tr>
				<tr>
					<td>送料</td>
					<td><%= @order.shipping_cost %>円</td>
				</tr>
				<tr>
					<td>総計</td>
					<td><%= @order.grand_total.to_s(:delimited) %>円</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>