config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/' => 'homes#top', as: 'top'
    get 'search' => 'items#search', as: 'search'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root 'homes#top'
    get 'search' => 'items#search', as: 'search'
    get '/about' => 'homes#about', as: 'about'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#new'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :orders, only: [:new, :index, :create, :show]
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def finally_address
  '〒' + postal_code + ' ' + destination + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders
  
  validates :first_name,presence:true
  validates :last_name,presence:true
  validates :first_name_kana,presence:true
  validates :last_name_kana,presence:true
  validates :postal_code,presence:true
  validates :address,presence:true
  validates :telephone_number,presence:true
  
  def full_name
    first_name + " " + last_name
  end
  
  def full_name_kana
    first_name_kana + " " + last_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  has_one_attached :image
  
  def with_tax_price
    (price * 1.1).ceil
    # ceilは切り上げ、floorが切り捨て、roundが四捨五入
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, confirm_deposit: 1, in_production: 2, preparing_shipment: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { cannot_start: 0, waiting_start: 1, in_production: 2, completed: 3 }
  
  def subtotal
    price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params  
    params.require(:genre).permit(:name)
  end  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  def search
    if params[:name].present?
      @items = Item.where('name like ?', "%#{params[:name]}%")
    else
      @items = Item.all
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :image, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <% if admin_signed_in? %>
            <a class="navbar-brand p-3 border" href="/admin"><span>LOGO</span></a>
          <% elsif customer_signed_in? %>
            <a class="navbar-brand p-3 border" href="/"><span>LOGO</span></a>
            <p>ようこそ、<%= current_customer.first_name %>さん！</p>
          <% else %>
            <a class="navbar-brand p-3 border" href="/"><span>LOGO</span></a>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li><%= link_to '商品一覧',  admin_items_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to '会員一覧',  admin_customers_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to '注文履歴一覧',  admin_top_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to 'ジャンル一覧',  admin_genres_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border mr-3' %></li>
              <% elsif customer_signed_in? %>
                <li><%= link_to 'マイページ', mypage_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to '商品一覧', items_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to 'カート', cart_items_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark border mr-3' %></li>
              <% else %>
                <li><%= link_to 'About', about_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to '商品一覧', items_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-dark border mr-3' %></li>
                <li><%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-dark border mr-3' %></li>
              <% end %>
            </ul>
          </div>
          <% if admin_signed_in? %>
            <%= form_with url: admin_search_path, method: :get do |f| %> <!-- 検索機能の実装 -->
              <%= f.text_field :name, :placeholder =>"Search" %>
              <%= f.submit "検索", class: "btn btn-primary" %>
            <% end %>
          <% else %>
            <%= form_with url: search_path, method: :get do |f| %>
              <%= f.text_field :name, :placeholder =>"Search" %>
              <%= f.submit "検索", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="text-center"></footer>
  </body>
</html>